Fail if a single procedure has different outcomes
dafny-lang/dafny-reportgenerator pull request #12
Opened 2022-06-28 23:31 UTC by atomb

Perhaps the most fundamental definition of verification instability is that the outcome of verification differs between verification attempts. The CSV input consumed by `dafny-reportgenerator` includes an `Outcome` field, and this PR now causes the `summarize-csv-results` command to fail if the number of distinct outcome types for a given procedure is greater than 1. Given that this is always an indication of instability, this check is unconditional.

2022-06-29 17:56 UTC, robin-aws requested changes
LGTM, but can you add at least one unit test for the new logic, since (hopefully) the CI here won't end up exercising it?

2022-06-29 19:03 UTC, atomb commented on src/TestResult.dfy
> +    |Seq.ToSet(Seq.Map((result : TestResult) => result.outcome, results))| == 1
Oh, yes, and I the PR you just merged already bumped to Dafny 3.7, so that's the way to go. :)

2022-06-29 19:07 UTC, atomb commented on src/TestResult.dfy
> +    |Seq.ToSet(Seq.Map((result : TestResult) => result.outcome, results))| == 1
Making a unit test for this is proving more difficult than expected, but it's easy to include a simple integration test in CI.

2022-06-30 16:50 UTC, robin-aws approved these changes
🚀

2022-06-30 21:10 UTC, merged